# Generated by Django 3.0.2 on 2020-01-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='code',
        ),
    ]
