# Generated by Django 3.0.2 on 2020-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_actions_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='params',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
