# Generated by Django 3.0.2 on 2020-01-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200121_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='route',
            new_name='name',
        ),
    ]
