# Generated by Django 3.0.2 on 2020-01-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200121_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='name',
            new_name='route',
        ),
    ]
