# Generated by Django 3.0.2 on 2020-01-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200121_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='active',
            new_name='is_active',
        ),
    ]
