# Generated by Django 3.0.2 on 2020-01-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.Action')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.Node')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.Scenario')),
            ],
        ),
    ]
