# Generated by Django 3.0.2 on 2020-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_scenarioactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
