# Generated by Django 3.0.2 on 2020-01-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_action_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='type',
            field=models.IntegerField(choices=[], default=0),
        ),
        migrations.AddField(
            model_name='scenarioactions',
            name='is_finished',
            field=models.BooleanField(default=0),
        ),
    ]
