# Generated by Django 3.0.2 on 2020-02-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20200202_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioactions',
            name='after_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
