# Generated by Django 3.0.2 on 2020-02-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_scenarioactions_after_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioactions',
            name='after_time',
        ),
    ]
