# Generated by Django 3.0.2 on 2020-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_remove_scenarioactions_after_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioactions',
            name='after_time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='scenarioactions',
            name='at_time',
            field=models.DateTimeField(default='2020-02-02 00:00:00'),
        ),
    ]
