# Generated by Django 3.0.2 on 2020-02-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20200202_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioactions',
            name='days',
        ),
        migrations.AddField(
            model_name='scenarioactions',
            name='at_day',
            field=models.CharField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='type',
            field=models.IntegerField(choices=[(0, 'One Time'), (1, 'Everyday'), (2, 'Workdays'), (3, 'Weekend'), (3, 'Day Of Week')], default=0),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.CharField(max_length=8),
        ),
    ]
