# Generated by Django 3.0.2 on 2020-02-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20200202_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScenarioActions',
            new_name='ScenarioAction',
        ),
    ]
