# Generated by Django 3.0.2 on 2020-02-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_auto_20200202_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioaction',
            name='after_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='scenarioaction',
            name='at_time',
            field=models.TimeField(default=''),
        ),
    ]
