# Generated by Django 3.0.2 on 2020-02-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_auto_20200202_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenarioaction',
            old_name='is_finished',
            new_name='is_executed',
        ),
    ]
