# Generated by Django 3.0.2 on 2020-02-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_auto_20200202_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenarioaction',
            name='after_time',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='type',
            field=models.IntegerField(choices=[(0, 'One Time'), (1, 'Delayed'), (2, 'Everyday'), (3, 'Workdays'), (4, 'Weekend'), (4, 'Day Of Week')], default=0),
        ),
    ]
