# Generated by Django 3.0.2 on 2020-02-04 08:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_auto_20200203_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 2, 4, 8, 31, 45, 846351, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
