# Generated by Django 3.0.2 on 2020-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_scenario_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioaction',
            name='at_time',
            field=models.TimeField(blank=True, default=''),
        ),
    ]
