# Generated by Django 3.0.2 on 2020-02-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20200206_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenarioaction',
            name='at_time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
